// Code generated by MockGen. DO NOT EDIT.
// Source: htmltoimage.go

// Package mock is a generated GoMock package.
package mock

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// GenerateByID mocks base method.
func (m *MockGenerator) GenerateByID(html, elementID string, out io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateByID", html, elementID, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateByID indicates an expected call of GenerateByID.
func (mr *MockGeneratorMockRecorder) GenerateByID(html, elementID, out interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateByID", reflect.TypeOf((*MockGenerator)(nil).GenerateByID), html, elementID, out)
}
