// Code generated by MockGen. DO NOT EDIT.
// Source: timeutil.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTimeFactory is a mock of TimeFactory interface.
type MockTimeFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTimeFactoryMockRecorder
}

// MockTimeFactoryMockRecorder is the mock recorder for MockTimeFactory.
type MockTimeFactoryMockRecorder struct {
	mock *MockTimeFactory
}

// NewMockTimeFactory creates a new mock instance.
func NewMockTimeFactory(ctrl *gomock.Controller) *MockTimeFactory {
	mock := &MockTimeFactory{ctrl: ctrl}
	mock.recorder = &MockTimeFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeFactory) EXPECT() *MockTimeFactoryMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockTimeFactory) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockTimeFactoryMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimeFactory)(nil).Now))
}
